config/routes.rb
HSBCUbs::Application.routes.draw do
  get "sale/new"

root to: "static_pages#index"

resources :sales

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  def new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "HSBCUbs" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>


    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>

  <body class="modern-ui">
    <div class="page">
      <div class="nav-bar">
        <div class="nav-bar-inner padding10">
          <span class="pull-menu"></span>

          <a href="/">
            <span class="element brand">
              <span class="icon-basket place-left"></span>
              <span class="name">BASTLI Kasse</span>
            </span>
          </a>

          <ul class="menu">
            <li><%= link_to "Home", "/" %></li>

            <li data-role="dropdown">
              <a href="#">Menu</a>
              <ul class="dropdown-menu">
                <li><%= link_to "Link1", "/path1" %></li>
                <li><%= link_to "Link2", "/path2" %></li>
                <li class="divider"></li>
                <li><%= link_to "Link3", "/path3" %></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>

      <div class="page-region">
        <div class="page-region-content">
          <div class="grid">
            <div class="row">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>




    </div>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/sales/new.html.erb
<div class="page secondary">
        <div class="page-header">
            <div class="page-header-content">
            <h1 id="head">Neuer Verkauf</h1>
            <a href="/" class="back-button big page-back"></a>
            </div>
        </div>
 
        <div class="page-region">
            <div class="page-region-content">
                ...
            </div>
        </div>
    </div>

app/views/static_pages/index.html.erb
<div id="menugrid" class="grid">
<div class="span7">
	<div class="row">

		<%= link_to new_sale_path, class:"tile double double-vertical bg-color-red" do %>
		
			<div class="tile-content">
				<i class="icon-cart" style="font-size:160px;"></i>

			</div>
			<div class="brand">
				<span class="name">Verkauf</span>

			</div>

		<% end %>

		

		<%= link_to new_sale_path, class:"tile double double-vertical bg-color-green" do %>

		<div class="tile-content">
				<i class="icon-history" style="font-size:160px;"></i>

			</div>
			<div class="brand">
				<span class="name">Offene Verkäufe</span>
				<span class="badge">8</span>

			</div>
			<% end %>





	</div>

	<div class="row">
		<div class="tile double double-vertical bg-color-blue">
			<div class="tile-content">
				<i class="icon-stats" style="font-size:160px;"></i>

			</div>
			<div class="brand">
				<span class="name">Statistiken</span>

			</div>

		</div>


	

			<div class="tile double double-vertical bg-color-yellow">
				<div class="tile-content">
				<i class="icon-search" style="font-size:160px;"></i>

			</div>
			<div class="brand">
				<span class="name">Bauteilesuche</span>

			</div>

		</div>
	</div>

</div>
<div class="span3">

<h1 id="uhr"></h1>
</div>
</div>